name: variacao_ativo
description: "Variacao do Ativo by Guide."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Provide Lints Rules
  flutter_lints: ^3.0.1
  dart_code_metrics: ^5.7.6


flutter:

  uses-material-design: true